### ISSUE TITLE
Create About Us Page Highlights Section

### ISSUE THREAD

**Issue by tylerlam1** [Code-the-Change-YYC/code-the-change-yyc-site#20]
![image](https://user-images.githubusercontent.com/41935461/183314306-5f2058bc-2c89-4a7b-bbb4-eca2cee854b4.png)

**Comment by harsohailB** [comment]
I don't see this on the figma. Where did you get this from? [This](https://github.com/Code-the-Change-YYC/code-the-change-yyc-site/issues/23) is what I see

**Comment by tylerlam1** [comment]
I think mine is outdated

**Comment by tylerlam1** [comment]
Fixed it
