### ISSUE TITLE
Add lazy loading for images

### ISSUE THREAD

**Issue by tylerlam1** [Code-the-Change-YYC/code-the-change-yyc-site#42]
Some high res images are loading hella slow. We should implement lazy loading for all images to speed things up

**Comment by harsohailB** [comment]
@tylerlam1 This is kind of tricky as NextJS is SSR so it serves the images as part of the entire page rather than pulling it after. Have any approaches in mind?

**Comment by tylerlam1** [comment]
@harsohailB Maybe see if you can convert the `img` components into `Image` components as described [here](https://nextjs.org/docs/basic-features/image-optimization). Looks like `Image` has some image loading optimization features.

**Comment by harsohailB** [comment]
Did that. It didnt help. Our images are way too high res

**Comment by tylerlam1** [comment]
@harsohailB I can give it a try. Do you maybe want to reorganize all the files in our components folder into organized subdirectories?
